// Command docgen regenerates the auto-produced guild reference docs
// under docs/generated/. It is the single source of truth pipeline:
//
//	spec / cobra tree  →  docgen  →  docs/generated/{cli,mcp}.md
//
// Run via `make docs`. `make docs-check` runs it in verify-mode (no
// writes; exits non-zero if output would diverge from disk).
//
// Not meant to be invoked by end users of the guild binary.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/google/jsonschema-go/jsonschema"
	sdkmcp "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/mathomhaus/guild/internal/cli"
	"github.com/mathomhaus/guild/internal/mcp"
)

const autogenBanner = "<!-- auto-generated by cmd/docgen — run `make docs` to regenerate. DO NOT EDIT. -->"

func main() {
	var outDir string
	var check bool
	flag.StringVar(&outDir, "out", "docs/generated", "output directory")
	flag.BoolVar(&check, "check", false, "verify-only: fail non-zero if output would differ from disk")
	flag.Parse()

	cliDoc, err := renderCLI(cli.Root())
	if err != nil {
		fatal("render cli: %v", err)
	}

	mcpDoc, err := renderMCP()
	if err != nil {
		fatal("render mcp: %v", err)
	}

	readme := renderReadme()

	files := map[string]string{
		"README.md": readme,
		"cli.md":    cliDoc,
		"mcp.md":    mcpDoc,
	}

	if check {
		if diffs := checkFiles(outDir, files); len(diffs) > 0 {
			for _, d := range diffs {
				fmt.Fprintln(os.Stderr, d)
			}
			fmt.Fprintln(os.Stderr, "\ndocs are stale — run: make docs")
			os.Exit(1)
		}
		fmt.Println("✓ generated docs match disk")
		return
	}

	if err := writeFiles(outDir, files); err != nil {
		fatal("write: %v", err)
	}
	fmt.Printf("✓ wrote %d file(s) to %s\n", len(files), outDir)
}

// ---------------------------------------------------------------------------
// CLI doc rendering
// ---------------------------------------------------------------------------

func renderCLI(root *cobra.Command) (string, error) {
	var b strings.Builder
	b.WriteString(autogenBanner)
	b.WriteString("\n\n# guild CLI reference\n\n")
	b.WriteString("Every `guild <verb>` subcommand generated from the live cobra tree.\n\n")

	// Collect every command (depth-first), skipping hidden ones.
	var cmds []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if sub.Hidden || sub.Name() == "help" {
				continue
			}
			cmds = append(cmds, sub)
			walk(sub)
		}
	}
	walk(root)
	sort.Slice(cmds, func(i, j int) bool {
		return cmds[i].CommandPath() < cmds[j].CommandPath()
	})

	// Table of contents.
	b.WriteString("## Verbs\n\n")
	for _, c := range cmds {
		path := c.CommandPath()
		anchor := strings.ReplaceAll(path, " ", "-")
		fmt.Fprintf(&b, "- [`%s`](#%s)", path, anchor)
		if c.Short != "" {
			fmt.Fprintf(&b, " — %s", c.Short)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")

	// Detail section per verb.
	for _, c := range cmds {
		renderCobraCmd(&b, c)
	}
	return b.String(), nil
}

func renderCobraCmd(b *strings.Builder, c *cobra.Command) {
	path := c.CommandPath()
	fmt.Fprintf(b, "## `%s`\n\n", path)
	if c.Short != "" {
		fmt.Fprintf(b, "%s\n\n", c.Short)
	}
	fmt.Fprintf(b, "**Usage**\n\n```\n%s\n```\n\n", c.UseLine())
	if len(c.Aliases) > 0 {
		fmt.Fprintf(b, "**Aliases:** %s\n\n", strings.Join(c.Aliases, ", "))
	}
	if c.Long != "" && c.Long != c.Short {
		fmt.Fprintf(b, "%s\n\n", c.Long)
	}

	var flags []*pflag.Flag
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		flags = append(flags, f)
	})
	if len(flags) > 0 {
		sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
		b.WriteString("**Flags**\n\n")
		b.WriteString("| flag | type | default | description |\n")
		b.WriteString("| --- | --- | --- | --- |\n")
		for _, f := range flags {
			short := ""
			if f.Shorthand != "" {
				short = ", `-" + f.Shorthand + "`"
			}
			def := f.DefValue
			if def == "" {
				def = "—"
			}
			fmt.Fprintf(b, "| `--%s`%s | %s | `%s` | %s |\n",
				f.Name, short, f.Value.Type(), def, oneLine(f.Usage))
		}
		b.WriteString("\n")
	}
}

// ---------------------------------------------------------------------------
// MCP doc rendering
// ---------------------------------------------------------------------------

func renderMCP() (string, error) {
	srv, err := mcp.BuildForDocs()
	if err != nil {
		return "", fmt.Errorf("build server: %w", err)
	}
	tools, err := listTools(srv)
	if err != nil {
		return "", fmt.Errorf("list tools: %w", err)
	}
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	var b strings.Builder
	b.WriteString(autogenBanner)
	b.WriteString("\n\n# guild MCP tool catalog\n\n")
	fmt.Fprintf(&b, "Every tool a registered MCP client sees. %d tools.\n\n", len(tools))

	b.WriteString("## Tools\n\n")
	for _, t := range tools {
		fmt.Fprintf(&b, "- [`%s`](#%s)", t.Name, t.Name)
		if t.Description != "" {
			fmt.Fprintf(&b, " — %s", firstSentence(t.Description))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")

	for _, t := range tools {
		renderTool(&b, t)
	}
	return b.String(), nil
}

func listTools(s *sdkmcp.Server) ([]*sdkmcp.Tool, error) {
	ctx := context.Background()
	clientT, serverT := sdkmcp.NewInMemoryTransports()
	serverSess, err := s.Connect(ctx, serverT, nil)
	if err != nil {
		return nil, err
	}
	defer func() { _ = serverSess.Wait() }()

	client := sdkmcp.NewClient(&sdkmcp.Implementation{Name: "guild-docgen"}, nil)
	sess, err := client.Connect(ctx, clientT, nil)
	if err != nil {
		return nil, err
	}
	defer func() { _ = sess.Close() }()

	res, err := sess.ListTools(ctx, &sdkmcp.ListToolsParams{})
	if err != nil {
		return nil, err
	}
	return res.Tools, nil
}

func renderTool(b *strings.Builder, t *sdkmcp.Tool) {
	fmt.Fprintf(b, "## `%s`\n\n", t.Name)
	if t.Description != "" {
		fmt.Fprintf(b, "%s\n\n", t.Description)
	}
	schema, _ := t.InputSchema.(*jsonschema.Schema)
	if schema == nil || len(schema.Properties) == 0 {
		b.WriteString("_no arguments_\n\n")
		renderRawSchema(b, t.InputSchema)
		return
	}
	// Render arg table from the schema.
	b.WriteString("**Arguments**\n\n")
	b.WriteString("| name | type | required | description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	required := map[string]bool{}
	for _, r := range schema.Required {
		required[r] = true
	}
	names := make([]string, 0, len(schema.Properties))
	for n := range schema.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		prop := schema.Properties[n]
		typ := prop.Type
		if typ == "" && len(prop.Types) > 0 {
			typ = strings.Join(prop.Types, "|")
		}
		if typ == "" {
			typ = "any"
		}
		req := ""
		if required[n] {
			req = "✓"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", n, typ, req, oneLine(prop.Description))
	}
	b.WriteString("\n")
	renderRawSchema(b, t.InputSchema)
}

func renderRawSchema(b *strings.Builder, schema any) {
	schemaJSON, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return
	}
	b.WriteString("<details><summary>Raw JSON schema</summary>\n\n```json\n")
	b.Write(schemaJSON)
	b.WriteString("\n```\n\n</details>\n\n")
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

func renderReadme() string {
	return autogenBanner + `

# guild — auto-generated reference

The files in this directory are regenerated from the live code by
` + "`cmd/docgen`" + `. Do not edit them by hand; edits are overwritten
on the next ` + "`make docs`" + ` run.

| file | contents |
| --- | --- |
| [` + "`cli.md`" + `](./cli.md) | ` + "`guild`" + ` CLI reference — every subcommand with flags + usage |
| [` + "`mcp.md`" + `](./mcp.md) | MCP tool catalog — every tool with arg schema |

To regenerate:

` + "```" + `
make docs
` + "```" + `

CI catches drift via ` + "`make docs-check`" + ` (exits non-zero if the
generated output differs from what's checked in).
`
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func writeFiles(dir string, files map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for name, body := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil { //nolint:gosec // generated docs are world-readable by design
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func checkFiles(dir string, files map[string]string) []string {
	var diffs []string
	for name, body := range files {
		path := filepath.Join(dir, name)
		onDisk, err := os.ReadFile(path)
		if err != nil {
			diffs = append(diffs, fmt.Sprintf("missing: %s", path))
			continue
		}
		if !bytes.Equal(onDisk, []byte(body)) {
			diffs = append(diffs, fmt.Sprintf("stale: %s", path))
		}
	}
	return diffs
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.TrimSpace(s)
}

func firstSentence(s string) string {
	s = oneLine(s)
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	return s
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "docgen: "+format+"\n", args...)
	os.Exit(1)
}
